Translate Response Formatting
apiflask/docs-zh pull request #11
Opened 2022-05-09 05:23 UTC by Tridagger

Checklist:

- [ ] 遵循[翻译排版和词汇要求](https://github.com/apiflask/docs-zh/wiki/Translation-Guide)。
- [ ] 执行 `tox -e docs`，处理错误。
- [ ] 检查文档预览，修复错别字和 Markdown 语法错误。

2022-05-11 14:53 UTC, greyli requested changes

2022-05-11 14:53 UTC, greyli commented on docs_zh/response.md
> +PetsOutSchema 类。
不要修改 Markdown 语法标记：

```suggestion
然后我们创建 `PetOutSchema` 类，和嵌套了 `PetOutSchema` 和 `PaginationSchema` 的
`PetsOutSchema` 类。
```

2022-05-11 14:53 UTC, greyli commented on docs_zh/response.md
> +在视图函数的返回值中，我们使用 `pagination_builder` 来构建分页数据，并通过 Flask-SQLAlchemy 传递 `pagination` 对象。
```suggestion
在视图函数的返回值中，我们使用 `pagination_builder` 来构建分页数据，并传递 Flask-SQLAlchemy 提供的 `pagination` 对象。
```

2022-05-11 14:53 UTC, greyli commented on docs_zh/response.md
> +如果你想使用自定义的分页类，请确保传递的 `pagination` 对象具有以下属性：
```suggestion
如果你在使用自定义的分页类，请确保传递的 `pagination` 对象具有以下属性：
```

2022-05-11 14:53 UTC, greyli commented on docs_zh/response.md
> +具体细节请参阅 [完整示例](https://github.com/apiflask/apiflask/blob/main/examples/pagination/app.py)
```suggestion
具体细节请参阅 [完整示例](https://github.com/apiflask/apiflask/blob/main/examples/pagination/app.py)。
```

2022-05-11 14:53 UTC, greyli commented on docs_zh/response.md
> +来了解更多详情。
```suggestion
你可以通过 `example` 和 `examples` 参数来为 OpenAPI spec 设置响应示例，请参阅 OpenAPI 支持章节中 [响应与请求示例](/openapi/#response-and-request-example) 一节来了解更多详情。
```

2022-05-11 14:53 UTC, greyli commented on docs_zh/response.md
> +字典 schema 的名称类似 `"Generated"`，可以用 `schema_name` 参数来指定 schema 名称：
```suggestion
字典 schema 的名称将会类似 `"Generated"`。要指定 schema 名称，可使用 `schema_name` 参数：
```

2022-05-11 14:55 UTC, greyli commented
P.S. 如果修改没问题的话，可以逐一点 Add suggestion to batch，然后统一 commit。

2022-05-12 02:03 UTC, Tridagger reviewed
update translation

2022-05-12 14:23 UTC, greyli approved these changes

2022-05-12 14:24 UTC, merged

2022-05-12 14:24 UTC, greyli commented
谢谢。下次建议用单独的分支创建 PR。