Translate Request Handling
apiflask/docs-zh pull request #15
Opened 2022-05-10 01:33 UTC by rice0208

Checklist:

- [x] 遵循[翻译排版和词汇要求](https://github.com/apiflask/docs-zh/wiki/Translation-Guide)。
- [x] 执行 `tox -e docs`，处理错误。
- [x] 检查文档预览，修复错别字和 Markdown 语法错误。

2022-05-12 15:02 UTC, greyli requested changes

2022-05-12 15:02 UTC, greyli commented on docs_zh/request.md
> +APIFlask 提供了以下定位点的支持：
```suggestion
APIFlask 支持使用下面的值来声明请求数据的位置：
```

2022-05-12 15:02 UTC, greyli commented on docs_zh/request.md
> +- `json` (默认)
括号需要更新，下同。

2022-05-12 15:03 UTC, rice0208 commented on docs_zh/request.md
> +!!! tips
不是我改的。

2022-08-24 04:40 UTC, merged

2022-08-24 04:40 UTC, greyli commented
改进了一些措辞和错别字（<https://github.com/apiflask/docs-zh/pull/15/commits/e5cf5be04821013cd6fb95f28a01a145e9d0e6d4>）。