Translate Swagger UI and Redoc
apiflask/docs-zh pull request #24
Opened 2022-05-13 10:46 UTC by Tridagger

Checklist:

- [ ] 遵循[翻译排版和词汇要求](https://github.com/apiflask/docs-zh/wiki/Translation-Guide)。
- [ ] 执行 `tox -e docs`，处理错误。
- [ ] 检查文档预览，修复错别字和 Markdown 语法错误。

2022-05-13 10:51 UTC, greyli commented
下次可以先创建认领章节的 PR，被合并后再开始翻译，避免有两个人重复翻译同一章节。

2022-05-13 10:52 UTC, Tridagger commented
> 下次可以先创建认领章节的 PR，被合并后再开始翻译，避免有两个人重复翻译同一章节。

OK  着急了

2022-06-12 14:12 UTC, greyli requested changes

2022-06-12 14:12 UTC, greyli commented on docs_zh/api-docs.md
> +`docs_path` 和 `redoc_path` 接受以斜杠开头的 URL 路径，因此您可以设置这样的前缀：
保持统一用词：
```suggestion
`docs_path` 和 `redoc_path` 接受以斜杠开头的 URL 路径，因此你可以设置这样的前缀：
```

2022-06-12 14:12 UTC, greyli commented on docs_zh/api-docs.md
> +或者同时禁用：
```suggestion
或者同时禁用两者：
```

2022-06-12 14:12 UTC, greyli commented on docs_zh/api-docs.md
> +## 禁用指定蓝图的 API 文档
之前合并的一章已经采用了「蓝本」，要不先统一用「蓝本」吧？
```suggestion
## 禁用指定蓝本的 API 文档
```

2022-06-12 14:12 UTC, greyli commented on docs_zh/api-docs.md
> +有关详细内容，请参阅 *[禁用指定蓝图的 OpenAPI 支持](/openapi/#disable-for-specific-blueprints)*。
某个章节的标题，是不是用书名号更符合中文的使用习惯？
```suggestion
有关详细内容，请参阅 *[禁用指定蓝本的 OpenAPI 支持](/openapi/#disable-for-specific-blueprints)*。
```

2022-06-12 14:12 UTC, greyli commented on docs_zh/api-docs.md
> +来查看配置变量的介绍和示例。
```suggestion
来查看这些配置变量的介绍和示例。
```

2022-06-12 14:12 UTC, greyli commented on docs_zh/api-docs.md
> +就同前面那样，如果想使用本地资源，可以传递本地静态文件的 URL 到相应的配置变量：
```suggestion
和上一节类似，如果想使用本地资源，可以传递本地静态文件的 URL 到相应的配置变量：
```

2022-06-12 14:12 UTC, greyli commented on docs_zh/api-docs.md
> +对于本地资源，您可以传递相对 URL 。 例如，如果你想在本地托管独立的 Redoc JavaScript 文件，请按照以下步骤操作：
中文标点前后不需要加空格。
```suggestion
对于本地资源，你可以传递相对 URL。例如，如果你想在本地托管独立的 Redoc JavaScript 文件，请按照以下步骤操作：
```

2022-06-12 14:12 UTC, greyli commented on docs_zh/api-docs.md
> +- 将文件放在您的 `static` 文件夹中，将其命名为 `redoc.standalone.js` 或其他。
```suggestion
- 将文件放在你的 `static` 文件夹中，将其命名为 `redoc.standalone.js` 或其他任意名称。
```

2022-06-12 14:12 UTC, greyli commented on docs_zh/api-docs.md
> +- 找出 js 文件的相对 URL。 如果文件在 `static` 文件夹中，那么 URL 将是 `/static/redoc.standalone.js`。如果你把它放到一个名为 `js` 的子文件夹里，那么 URL 则是 `/static/js/redoc.standalone.js`。
```suggestion
- 确定 js 文件的相对 URL。 如果文件在 `static` 文件夹中，那么 URL 将是 `/static/redoc.standalone.js`。如果你把它放到一个名为 `js` 的子文件夹里，那么 URL 则是 `/static/js/redoc.standalone.js`。
```

2022-06-12 14:12 UTC, greyli commented on docs_zh/api-docs.md
> +- 使用 `npm init` 初始化 `static` 文件夹中的 npm。
```suggestion
- 使用 `npm init` 在 `static` 文件夹中初始化 npm。
```

2022-06-12 14:12 UTC, greyli commented on docs_zh/api-docs.md
> +[_swagger_ui_releases]: https://github.com/swagger-api/swagger-ui/releases
保持原有缩进：
```suggestion
    [_swagger_ui_releases]: https://github.com/swagger-api/swagger-ui/releases
```

2022-06-12 14:15 UTC, greyli commented
如果改动建议没问题的话，可以在 files 页面点每一个修改建议下面的「Add suggestion to batch」，然后统一 commit。

2022-06-13 14:42 UTC, merged

2022-06-13 14:43 UTC, greyli commented
Merged, thanks!